#include "utils/sfmlFct.hpp"

uint8_t sfmlKeyToSAPHYRKey(sf::Keyboard::Key key)
{
    switch (key)
    {
    // letters
    case sf::Keyboard::A:
        return 0x41;
    case sf::Keyboard::B:
        return 0x42;
    case sf::Keyboard::C:
        return 0x43;
    case sf::Keyboard::D:
        return 0x44;
    case sf::Keyboard::E:
        return 0x45;
    case sf::Keyboard::F:
        return 0x46;
    case sf::Keyboard::G:
        return 0x47;
    case sf::Keyboard::H:
        return 0x48;
    case sf::Keyboard::I:
        return 0x49;
    case sf::Keyboard::J:
        return 0x4A;
    case sf::Keyboard::K:
        return 0x4B;
    case sf::Keyboard::L:
        return 0x4C;
    case sf::Keyboard::M:
        return 0x4D;
    case sf::Keyboard::N:
        return 0x4E;
    case sf::Keyboard::O:
        return 0x4F;
    case sf::Keyboard::P:
        return 0x50;
    case sf::Keyboard::Q:
        return 0x51;
    case sf::Keyboard::R:
        return 0x52;
    case sf::Keyboard::S:
        return 0x53;
    case sf::Keyboard::T:
        return 0x54;
    case sf::Keyboard::U:
        return 0x55;
    case sf::Keyboard::V:
        return 0x56;
    case sf::Keyboard::W:
        return 0x57;
    case sf::Keyboard::X:
        return 0x58;
    case sf::Keyboard::Y:
        return 0x59;
    case sf::Keyboard::Z:
        return 0x5A;

    // numbers
    case sf::Keyboard::Num0:
    case sf::Keyboard::Numpad0:
        return 0x30;
    case sf::Keyboard::Num1:
    case sf::Keyboard::Numpad1:
        return 0x31;
    case sf::Keyboard::Num2:
    case sf::Keyboard::Numpad2:
        return 0x32;
    case sf::Keyboard::Num3:
    case sf::Keyboard::Numpad3:
        return 0x33;
    case sf::Keyboard::Num4:
    case sf::Keyboard::Numpad4:
        return 0x34;
    case sf::Keyboard::Num5:
    case sf::Keyboard::Numpad5:
        return 0x35;
    case sf::Keyboard::Num6:
    case sf::Keyboard::Numpad6:
        return 0x36;
    case sf::Keyboard::Num7:
    case sf::Keyboard::Numpad7:
        return 0x37;
    case sf::Keyboard::Num8:
    case sf::Keyboard::Numpad8:
        return 0x38;
    case sf::Keyboard::Num9:
    case sf::Keyboard::Numpad9:
        return 0x39;

    // symbols
    case sf::Keyboard::Comma:
        return 0x3C;
    case sf::Keyboard::Period:
        return 0x3E;
    case sf::Keyboard::LBracket:
        return 0x5B;
    case sf::Keyboard::RBracket:
        return 0x5D;
    case sf::Keyboard::Tilde:
        return 0x5E;
    case sf::Keyboard::Slash:
        return 0x3F;
    case sf::Keyboard::SemiColon:
        return 0x3A;
    case sf::Keyboard::Quote:
        return 0x3B;
    case sf::Keyboard::Backslash:
        return 0x5C;
    case sf::Keyboard::Equal:
        return 0x3D;
    case sf::Keyboard::Hyphen:
        return 0x40;

    // special
    case sf::Keyboard::Backspace:
        return 0x08;
    case sf::Keyboard::Tab:
        return 0x09;
    case sf::Keyboard::Escape:
        return 0x1B;
    case sf::Keyboard::Enter:
        return 0x0D;
    case sf::Keyboard::Space:
        return 0x20;
    case sf::Keyboard::Delete:
        return 0x7F;

    // arrows
    case sf::Keyboard::Up:
        return 0x01;
    case sf::Keyboard::Down:
        return 0x02;
    case sf::Keyboard::Right:
        return 0x03;
    case sf::Keyboard::Left:
        return 0x04;

    // unknown
    default:
        return 0;
    }
}
